version: '2'
services:
  web:
    image: web
    build: .
    links:
      - redis
    ports:
      - '4545:4545'
  redis:
    image: redis
  sidekiq:
    image: web
    ports: 
      - 80
    depends_on:
      - redis
  postgres:
    image: postgres

